# Generated by Django 5.1.1 on 2024-09-06 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('important_dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdate',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importantdate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
